# groupsを使って、モノレポ全体の依存関係更新を一つのPRにまとめる
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    
    groups:
      monorepo-deps:
        patterns:
          - "*" 

  