name: frontend-deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}

    defaults:
        run:
            working-directory: frontend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with: 
          version: latest

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'pnpm'
          cache-dependency-path: 'pnpm-lock.yaml'

      - name: Enable corepack (pnpmの利用準備)
        run: corepack enable

      - name: Install frontend dependencies
        run: pnpm install

      #モノレポなので、型チェックを通すために、backendの型も必要
      - name: copy env file
        run: cp .env.example .env
        working-directory: backend
      #モノレポなので、型チェックを通すために、backendの型も必要
      - name: wrangler type generation
        run: pnpm exec wrangler types 
        working-directory: backend

      - name: opnenext build
        run: pnpm exec opennextjs-cloudflare build

      - name: Deploy Worker
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: 'frontend' 
          secrets: |
            NEXT_PUBLIC_API_URL
